[[redirects]]
  from = "/api*"
  to = "https://m3w5-auth-be.herokuapp.com/:splat"
  status = 200
  force = true

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    X-From = "Netlify"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Allow-Methods = "POST"